Removed closures in favour of private static methods to close issue #906
morelinq/MoreLINQ pull request #1064
Opened 2024-04-25 16:10 UTC by JacobSilasBentley

PR to close issue #906 where closures are to be removed in favour of using private static methods.

One unit test had to be updated. This was to change the max enumerations of the test sequence from 1 to 2. The test enumerates the sequence twice so this should have always been the case. However I think previously using closures meant that test was enumerated once when it should have been twice. Happy to be corrected if I have misunderstood.

This is my first PR for MoreLINQ so apologies if I have missed any guidance on submitting PRs and will happily take onboard feedback

2024-04-27 14:39 UTC, atifaziz requested changes
> This is my first PR for MoreLINQ so apologies if I have missed any guidance on submitting PRs and will happily take onboard feedback

First and foremost, welcome and thank you for your initiative to help with #906.

> One unit test had to be updated. This was to change the max enumerations of the test sequence from 1 to 2. The test enumerates the sequence twice so this should have always been the case. However I think previously using closures meant that test was enumerated once when it should have been twice. Happy to be corrected if I have misunderstood.

Actually you've uncovered a bug that I've documented in #1065! It seems that the sequence was accidentally getting cached by an update of the captured closure. Now that that's not happening with this PR, the test failed. I've proposed the correct fix to the test, which is to materialise the result of `Rank` before asserting. I've also edited the description of this PR to say it fixes #1065.

While you seem to have addressed the bulk of methods, the following may have slipped:

- [`Cartesian`](https://github.com/morelinq/MoreLINQ/blob/9e8073d8b502fbc91697d3cdb25b97a23d71a6c4/MoreLinq/Cartesian.g.tt#L118)
- [`Subsets`](https://github.com/morelinq/MoreLINQ/blob/9e8073d8b502fbc91697d3cdb25b97a23d71a6c4/MoreLinq/Subsets.cs#L116-L120)
- [`Await`](https://github.com/morelinq/MoreLINQ/blob/9e8073d8b502fbc91697d3cdb25b97a23d71a6c4/MoreLinq/Experimental/Await.cs#L431)
- [`Batch`](https://github.com/morelinq/MoreLINQ/blob/9e8073d8b502fbc91697d3cdb25b97a23d71a6c4/MoreLinq/Experimental/Batch.cs#L148) (Experimental)
- [`Memoize`](https://github.com/morelinq/MoreLINQ/blob/9e8073d8b502fbc91697d3cdb25b97a23d71a6c4/MoreLinq/Experimental/Memoize.cs)
- [`Merge`](https://github.com/morelinq/MoreLINQ/blob/9e8073d8b502fbc91697d3cdb25b97a23d71a6c4/MoreLinq/Experimental/Async/Merge.cs#L90)

If we can address those too, as well as some of the feedback, then we should be in a good position to get this merged.

2024-04-27 14:39 UTC, atifaziz commented on MoreLinq/CountDown.cs
> +                IEnumerable<T> source,
`source` isn't used or needed here.

2024-04-27 14:39 UTC, atifaziz commented on MoreLinq/CountDown.cs
> +                IEnumerable<T> source,
`source` isn't used or needed here.

2024-04-29 05:19 UTC, JacobSilasBentley commented on MoreLinq/SortedMerge.cs
> +            static IEnumerable<TSource> Impl(Func<TSource, TSource, bool> precedenceFunc, IEnumerable<IEnumerable<TSource>> sequences)
This has been updated.

2024-04-29 05:20 UTC, JacobSilasBentley commented on MoreLinq/EndsWith.cs
> +            static bool Impl(IEnumerable<T> snd, int count, IEnumerable<T> first, IEqualityComparer<T> comparer)
First has been moved and 'snd' renamed to 'second'

2024-04-29 07:06 UTC, JacobSilasBentley commented on MoreLinq/CountDown.cs
> +                IEnumerable<T> source,
Removed the unused argument.

2024-04-29 07:06 UTC, JacobSilasBentley commented on MoreLinq/CountDown.cs
> +                IEnumerable<T> source,
Removed the unused argument.

2024-04-29 07:27 UTC, JacobSilasBentley commented
Thank you for the warm welcome and the feedback!

I have hopefully addressed the requested changes and updated the methods that I missed in the initial PR.
 
'Memoize' might take a little bit more attention as unlike the other methods this method is a member of a non-static class. I'm not entirely sure if there is an advantage to making the method static in this scenario. At least one advantage could just be consistency. I would be interested in your opinion. For now, I have made the method static.

Let me know if there are any further issues for me to address.

2024-04-29 20:59 UTC, atifaziz requested changes
> I have hopefully addressed the requested changes and updated the methods that I missed in the initial PR.

Thank you for all the follow-up!

> 'Memoize' might take a little bit more attention as unlike the other methods this method is a member of a non-static class. I'm not entirely sure if there is an advantage to making the method static in this scenario. At least one advantage could just be consistency. I would be interested in your opinion. For now, I have made the method static.

Thanks for bringing this case to my attention. I think the right call here may be to simply remove the local function and inline its body. I believe it was separated for clarity rather than consistency and one doesn't need a local function here since `GetEnumerator` has no arguments and therefore no eager validation is needed.

> Let me know if there are any further issues for me to address.

I addressed some minor formatting changes directly (with commits aca7772f0fa569b40d227acb721bd15a81b7d9bf and b6608c448604545f7249d54e267b297a6f4105aa) as they were awkward to point out in the PR review UI.

If we can address `Memoize` then this is good to merge so nearly there! 🏁

2024-04-29 21:10 UTC, viceroypenguin commented
> 'Memoize' might take a little bit more attention as unlike the other methods this method is a member of a non-static class. I'm not entirely sure if there is an advantage to making the method static in this scenario. At least one advantage could just be consistency. I would be interested in your opinion. For now, I have made the method static.

When re-implementing this class/iterator, I found that splitting the initialization and enumeration code useful. With two methods, neither of which is static, the whole thing became easier to reason about. There are also some corner cases that are not currently covered, such as a reset and re-initialization happening between two `MoveNext()` calls. You can see my implementation [here](https://github.com/viceroypenguin/SuperLinq/blob/master/Source/SuperLinq/Memoize.cs#L59-L198) and feel free to adapt whatever you feel is best.

2024-04-30 08:41 UTC, JacobSilasBentley commented
> Thanks for bringing this case to my attention. I think the right call here may be to simply remove the local function and inline its body. I believe it was separated for clarity rather than consistency and one doesn't need a local function here since `GetEnumerator` has no arguments and therefore no eager validation is needed.

@atifaziz I've changed the method so it is no longer static and following @viceroypenguin suggestion, I've split the initialisation logic and enumeration logic into two different private non-static methods. This has the benefit of the method not being too long. Happy to inline both methods if you would prefer that approach.

@viceroypenguin also mentions: 
>There are also some corner cases that are not currently covered, such as a reset and re-initialization happening between two MoveNext() calls

I'm happy to look into this but I think it would be more appropriate to do this on a separate issue and separate PR

2024-04-30 11:49 UTC, atifaziz commented
> Happy to inline both methods if you would prefer that approach.

@JacobSilasBentley Actually, I would completely revert the change and leave `Memoize` alone in this PR. The length of the method isn't a real concern and any complexity is incidental (the split even adds more ceremony). I don't think the closure can be avoid here and exists even with the split. The bigger problem with inlining entirely is that it changes the semantics and behaviour and we don't have a test covering that otherwise it would've failed (would be good to eventually add the test). I feel this part of `Memoize` may need more thought, whether initialisation out to be lazy as it usually is with most iterator methods, but I'd say #906 doesn't apply in its case. It's not where we're looking to save a closure.

> I'm happy to look into this but I think it would be more appropriate to do this on a separate issue and separate PR

Agree, it should be a separate PR, but it would be good to first file those corner cases as demonstratable issues that need prioritising.

2024-05-01 11:04 UTC, JacobSilasBentley commented
@atifaziz I have reverted all changes made to the Memoize method made in this PR. 

Let me know if there are any remaining changes required before this code is merged in.

2024-05-01 12:06 UTC, atifaziz approved these changes
LGTM and thank you for all your help with contributing this!

2024-05-01 12:21 UTC, merged